query SearchReceipe {
  documents(acronym: "Receitas", fields: ["id","id_sku", "titulo", "data", "conteudo", "produtos"], account: "estagioacct") {
    id,
    fields {
      key
      value
    }
  }
}